# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24b3085bf30ec71eed58226bf892e2e69432b4fe5c0ab57c3729398b3b461e64c7b9f70e38685a5d37d69e3c560ef7506a1fe3ffce9e68c8f05cf7b4254a7cf1

test:
  secret_key_base: 4e88566facc41cd938c2483c3fc3f825e88baf20bd5733fc68351c98f5f74c3a81a3fa2e9043cac225337965037c8bbcd89eb7cc3d1c3c6785c0c2ceae660581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
